// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTest1.Data;

namespace WebApiTest1.Migrations
{
    [DbContext(typeof(WebApiTest1Context))]
    partial class WebApiTest1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiTest1.Models.DietApi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageDiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientDiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameDiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertiesDiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueDiet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DietApi");
                });
#pragma warning restore 612, 618
        }
    }
}
